### ISSUE TITLE
最新版本ctp接口app有没有？

### ISSUE THREAD

**Issue by abdeweili** [dev8gaby9fan/FutureDemo#1]
最新版本ctp接口app有没有？可以付费获取

**Comment by dev8gaby9fan** [comment]
现在项目依旧使用的是旧版本的CTP API，由于已经离开这个行业比较久了，不太清楚CTP的接口新增了哪些内容，但是主要的接口还是没有发生变化，如果你需要新接口的支持，建议你去官方的社区(QQ群)咨询一下。
最近优化了一下快期的行情、合约加载逻辑。希望我的项目能对你有所帮助。
